### ISSUE TITLE
Question / potential feature request: obtain band structure from vasprun.xml instead of PROCAR

### ISSUE THREAD

**Issue by smheidrich** [lucydot/effmass#16]
Perhaps this is a stupid question (sorry if it is), but is it really required to have a ``PROCAR`` file (only obtained if one runs VASP with ``LORBIT = 11``) to obtain the full band structure? pymatgen [is able to parse it from ``vasprun.xml``](https://pymatgen.org/pymatgen.io.vasp.outputs.html#pymatgen.io.vasp.outputs.BSVasprun) without the user having to run VASP with any additional parameters, and since effmass depends on pymatgen anyway, it would be great (IMHO) if that was provided as an alternative option for how to obtain it.

Or is there some advantage to ``PROCAR`` that I'm not seeing?

**Comment by lucydot** [comment]
Not a stupid question at all - this would make a lot of sense for the reasons you outline. The only reason it isn't implemented is because I haven't had the time to do so (and `effmass` should make much more use of the excellent pymatgen library). I'm in the middle of thesis writing, so can't take on any feature requests until August/September time when thesis handed in - I'll label the issue as enhancement, and if someone else wants to work on it before I get a chance to they are very welcome. Thanks for raising the issue - Lucy

**Comment by smheidrich** [comment]
Excellent, thank you very much & good luck with your thesis!

**Comment by lucydot** [comment]
Hi @smheidrich you raised this a while ago, but just a quick update that the latest Pull Request (#37) has support for (multiple) `vasprun.xml` files. After some testing this will be pulled into the main branch in the next week or so.

**Comment by smheidrich** [comment]
@lucydot Great, thanks! :+1:
