### ISSUE TITLE
Error loading a spin-polarised calculation

### ISSUE THREAD

**Issue by ajjackson** [lucydot/effmass#7]
I ran an LDA band structure for MgO. With no spin enabled it reads in ok, but when I set ISPIN=2 and recalculated the band structure effmass seems to have trouble reading the files.

Are spin-polarized calculations supported? I see that `effmass.inputs.Data` has an attribute for the number of spin channels, but I get an error while the object is being instantiated.

[spin_test.zip](https://github.com/lucydot/effmass/files/2220462/spin_test.zip)

**Comment by lucydot** [comment]
I've made a couple of changes to the `effmass.inputs` module and the latest commit works for me on the data you have sent across. The read in errors were due to having two k-point blocks (one for spin up, one for spin down) in the PROCAR file when ISPIN=2. I should write some tests for spin-polarized calculations (SoC calculations are already supported and tested), but I will leave that for a later date.

**Comment by ajjackson** [comment]
This is reading in for me now, but I'm not sure the results are consistent?

Here's a non-spin-polarised (closed-shell) calculation on the same system.  [test_mgo_nospin.zip](https://github.com/lucydot/effmass/files/2225297/test_mgo_nospin.zip)
(The setup was somewhat sloppy, so small differences are to be expected.)

Over the segment 5.33 eV [0. 0. 0.] -> [0.05 0.05 0.05] the _effmass_ methods all give me an effmass around 0.37, while in the spin-polarised case over the segment 5.00 eV [0. 0. 0.] -> [0.025 0.025 0.025] effmass is giving me 0.089 with all three methods.
(The last line of effmass_test.py needs to be changed to `display_effmasses(segments[-7])` to select this segment.)

By comparison, sumo-bandstats gives an effective mass of 0.375 for G->L in the closed-shell calculation and 0.350 for G->L in the open-shell calculation.

**Comment by lucydot** [comment]
Thanks for finding this problem @ajjackson - the latest commit on master has fixed it and results for the spin-polarised case are now consistent with Sumo (0.35 calculated by all three methods for 5.00 eV [0. 0. 0.] -> [0.025 0.025 0.025]). The problem arose partly because the data structures I am using are not ideal - a task on the todo list is to store the data in a pandas array rather than numpy arrays.

**Comment by ajjackson** [comment]
Great! That case looks good now.

I'm having trouble loading other cases though, with errors like:
```
Traceback (most recent call last):
  File "./effmass_test.py", line 10, in <module>
    data = effmass.inputs.Data("OUTCAR", "PROCAR")
  File "/home/adam/src/effmass/effmass/inputs.py", line 117, in __init__
    self.number_of_bands).T[i][:284]
ValueError: could not broadcast input array from shape (284) into shape (318)
```

That hard-coded "284" in _effmass.inputs_ looks suspicious, it's the same as the number of k-points in the test case!

**Comment by lucydot** [comment]
Ah yes, and it slipped through testing as I've not any spin-polarised test cases yet - I'll fix it now.

**Comment by lucydot** [comment]
I have removed the hard coded value for number of kpoints, and this latest commit works for me now on a different test calculation.

**Comment by ajjackson** [comment]
I'm running into e.g.
```
IndexError: index 24 is out of bounds for axis 0 with size 24
```
when trying to instantiate `Data`

[ge-band-squash-split.zip](https://github.com/lucydot/effmass/files/2245211/ge-band-squash-split.zip)

**Comment by lucydot** [comment]
This needs a test to catch mistakes - are you ok with me using the latest spin-polarised data you have posted as a test case?

**Comment by lucydot** [comment]
Ok - with the latest commit to master you should be able to instantiate the Data class for spin-polarised cases. Also, Travis will  automatically test effmass for the Ge spin-polarised data.

**Comment by ajjackson** [comment]
Looks good to me! It seems like a good idea to have test cases for all the various spin/SOC combinations.
