### ISSUE TITLE
Handling negative occupancy 

### ISSUE THREAD

**Issue by lucydot** [lucydot/effmass#9]
`effmass` should give a warning when there are negative occupancies generated from using the tetrahedron or MP-smearing scheme in vasp. See [this PR](https://github.com/bjmorgan/vasppy/pull/7).

**Comment by lucydot** [comment]
The Vasp documentation [here](http://cms.mpi.univie.ac.at/vasp/guide/node124.html) only mentions negative occupancies when using the MP scheme; @yw-fang are you finding negative occupancies using gaussian smearing?

If negative occupancies are only found for the MP scheme, I think raising a warning in `effmass` when there are negative occupancies will suffice (as the MP scheme is not recommended for semiconductors).

**Comment by bjmorgan** [comment]
A note that `vasppy` will now issue a warning by default if it reads a `PROCAR` file with negative occupancies (version 0.4.0.9).

See https://github.com/bjmorgan/vasppy/pull/7

**Comment by yw-fang** [comment]
@lucydot 

For myself, I haven't found negative occupancy calculated by tetrahedron method. However, as said by the admin of the vasp forum, such a case may exist, and those negative occupancies can be removed by using a proper SIGMA of Gaussian method instead of the tetrahedron method. (please see
 http://cms.mpi.univie.ac.at/vasp-forum/viewtopic.php?t=12532)

By the way, is current effmass code also applicable for analyzing the effective mass of metals and doped semiconductors? Thanks very much.

**Comment by lucydot** [comment]
I've also added a warning when there is negative occupancy, and `effmass` will automatically set negative occupancies to zero.

@yw-fang `effmass` is designed for use with semiconductors, but can be adapted for use for other materials (with care, as it hasn't been designed with this in mind). `effmass` determines the band structure extrema (VBM/CBM) from occupancy, assuming that the material is a non-degenerate semiconductor. 

However, you can manually set the extrema point and generate the bandstructure segments around this extrema point using the function `extrema.generate_segments` and setting the keyword `bk` manually.
